### ISSUE TITLE
Auto start fix

### ISSUE THREAD

**Issue by ghost** [29039/chrome-remote-desktop-fixer#1]
Can you make a fix that force the service to start on boot?
It won't startup even it's set to Automatic, it's so annoying
![image](https://user-images.githubusercontent.com/70694330/107620462-0497a880-6c55-11eb-9552-15a8c8e158fb.png)

**Comment by 29039** [comment]
I think that you must be having some other issue than what this script is intended to resolve.

Can you please tell me if pressing the Start button in this dialog actually works to start the service and if it actually stays in the Running state, say 5 minutes after closing the Dialog and going back in?

**Comment by 29039** [comment]
closing as no response

**Comment by ghost** [comment]
Sorry for late reply, I have changed to Automatic (Delayed), it has solved the problem

**Comment by 29039** [comment]
> Sorry for late reply, I have changed to Automatic (Delayed), it has solved the problem

Sorry for my late reply. Great to hear! If you want to use my script in conjunction with that tweak to make sure your CRD stays active and not put itself into Manual, just tweak the script to use AutomaticDelayedStart instead of Automatic after the -StartupType
